name = "jaga-cuan-backend"
main = "src/index.ts"
compatibility_date = "2026-03-10"

[vars]
APP_ENV = "dev"

[observability.logs]
enabled = true

[env.staging.vars]
APP_ENV = "staging"

[env.production.vars]
APP_ENV = "prod"
